name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag simple-web-api-gh:latest
    
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-web-api-gh:latest
      continue-on-error: true # Continuar incluso si la carga falla

    - name: Clean up
      run: docker logout
      if: always() # Se ejecutar치 incluso si un paso anterior falla

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure() # Ejecutar solo si el trabajo de construcci칩n fall칩
    steps:
    - name: Send failure notification
      run: echo "La construcci칩n y carga de la imagen de Docker fallaron. Por favor, verifique el flujo de trabajo."
